version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@1.0.2

workflows:
  test:
    jobs:
      - build-and-test:
          context: Test

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: set DATABASE_URL=$DATABASE_URL && set NODE_OPTIONS=$NODE_OPTIONS && npm test --maxWorkers=2 --max_old_space_size=4096
      - codecov/upload:
          file: './coverage/clover.xml'
          token: $CODECOV_TOKEN
